# version: '3'
# services:
#   redis:
#     container_name: redis
#     image: redis:latest
#     restart: always
#     networks:
#       - default
#     ports:
#       - 6379:6379
#   book_storeapp:
#     container_name: book_storeapp
#     # build:
#       # context: .
#       # dockerfile: Dockerfile
#     image: inferencelabsdeploy/books-store-app:latest
#     restart: always
#     networks:
#       default:
#     ports:
#       - 5000:5000
#     command: 
#       - python
#       - app.py
#     working_dir: /app
#     volumes: 
#       - /home/azureuser/Inference_converseAI/NewAPI_scratch:/app
#     depends_on:
#       - redis

version: '3'

services:
  redis:
    container_name: redis
    image: redis:latest
    restart: always
    networks:
      - default
    ports:
      - 6379:6379

  book_storeapp:
    container_name: book_storeapp
    image: inferencelabsdeploy/books-store-app:latest
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app.py
    command: ["flask", "run", "--host=0.0.0.0"]
    depends_on:
      - redis

  # db:
  #   image: postgres:latest
  #   environment:
  #     - POSTGRES_DB=mydatabase
  #     - POSTGRES_USER=myuser
    #     - POSTGRES_PASSWORD=mypassword

networks:
  default:
    driver: bridge
