

version: '3'

services:
  book_storeapp:
    # build:
      # context: .
      # dockerfile: Dockerfile
    container_name: book_storeapp
    image: inferencelabsdeploy/books-store-app:latest
    
    restart: always
    ports:
      - 5000:5000
    command: 
      - python
      - app.py
      - 0.0.0.0:5000
    working_dir: /app

    # environment:
    #   - FLASK_APP=app.py
    #   - FLASK_RUN_HOST=0.0.0.0
    # depends_on:
    #   - db

  # db:
  #   image: postgres:latest
  #   environment:
  #     - POSTGRES_DB=mydatabase
  #     - POSTGRES_USER=myuser
  #     - POSTGRES_PASSWORD=mypassword

networks:
  default:
    driver: bridge
